project:
  type: website
  output-dir: docs

website:
  title: "Train the Trainer: Student Track: Pedagogical Content"
  page-navigation: true
  navbar:
    right:
      - about.qmd
    left:
      - href: index.qmd
        text: Home
      - href: help.qmd
        text: Help
  sidebar:
    style: "docked"
    collapse-level: 1
    contents:
      - section: "Template Module"
        contents:
          - href: materials/PMM-template-module/PMM-template.qmd
      - section: "Module 1: Didactics 101"
        contents:
          - href: materials/PMM-M1/PMM-M1-S1-Constructive-Alignment/PMM-M1-S1-Constructive-Alignment.qmd
      - section: "Module 4: Leadership Skills"
        contents:
          - href: materials/PMM-M4/PMM-M4-S3-Citation-Politics/PMM-M4-S3-Citation-Politics.qmd


format:
  html:
    theme:
      - cosmo
      - brand
    css: website-custom.css
    toc: true
